### PR TITLE
Fix import statement for distributed.Queue

### LINKED ISSUE #8: ImportError: cannot import name 'Queue' from 'distributed.compatibility'
I am using dask_tensorflow but its giving me this error

### PR DESCRIPTION
**Pull request by bgroenks96**
Simple fix for the import error, as described in #8

Resolves #8

### CODE REVIEW

**Comment by CMobley7** [comment]
Any reason this hasn't been merged in yet?

**Comment by quasiben** [comment]
TravisCI is failing probably due to lack of py2.7  support in dask.  @TomAugspurger i can take on upgrading the CI but wanted to get your thoughts first before I do that.  Ideally we should get CI up and running again before merging this PR

**Comment by TomAugspurger** [comment]
Just merging is probably best. IMO fixing the CI isn't especially valuable
right now.

**Comment by quasiben** [comment]
@TomAugspurger, I don't have admin rights to merge.  Can you ?

**Comment by TomAugspurger** [comment]
Actually, I'm not sure the change here is correct. The old import was for `Queue.Queue` (py2) or `queue.Queue` (py3). This is changing it to `distributed.Queue` which may behave differently (not sure). @bgroenks96 can you change it to just `queue.Queue`?

**Comment by mrocklin** [comment]
distributed.Queue is definitely not the same as queue.Queue

**Comment by bgroenks96** [comment]
@TomAugspurger Nice catch, sorry about that. Fixed with c0812c5

**Comment by TomAugspurger** [comment]
Thanks @bgroenks96!

**Pull request merged**
